# Answer: 76576500
# Problem 12: Highly divisible triangular number
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 +2 +3 +4 +5 +6 +7 =28. The first ten terms would be:
# 1,3,6,10,15,21,28,36,45,55,…
# Let us list the factors of the first seven triangle numbers:
# 𝟏	:1
# 𝟑	:1,3
# 𝟔	:1,2,3,6
# 𝟏𝟎	:1,2,5,10
# 𝟏𝟓	:1,3,5,15
# 𝟐𝟏	:1,3,7,21
# 𝟐𝟖	:1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

import math

def count_divisors(n):
    count = 0
    for i in range(1, int(math.sqrt(n)) + 1):
        if n % i == 0:
            if i == n // i:
                count += 1
            else:
                count += 2
    return count

def solve():
    n = 1
    while True:
        triangle = n * (n + 1) // 2
        if count_divisors(triangle) > 500:
            return triangle
        n += 1

if __name__ == "__main__":
    print(solve())